# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 4edef1bbe8d6d5c5f7b27714bb5da901b7d2939a3089f81fa583415fd3d68243ce3e23fd7a3af0a882f8ece1d08559561fa8cbd7800ceaf1470f36ff23b777f1

test:
  secret_key_base: baed892735e587ab175361edc55b9c8678b183983e3d8ace5b00a9f1fc44999223d3dacf88c5685b24bb1fae889d0e33d713648520c26b39865936e83d13f488

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
